#!/bin/bash

PROJECT=$1
SCRIPT="${2:-start}"
METHOD="${3:-raw}"
OUTPUT=""


if [[ "$METHOD" == docker ]]
then
    cd $PROJECT
    CONTAINER="${4:-node}"
    OUTPUT=$(docker compose run --rm --detach --service-ports $CONTAINER npm run $SCRIPT)
else
    cd $PROJECT && npm run $SCRIPT &
    sleep 2
    PORT="${4:-3000}"
    OUTPUT=$(lsof -i:$PORT | grep -P 'node    \d+' -o | grep -P '\d+' -o)

    if [[ "$OUTPUT" == "" ]]
    then
        OUTPUT=$(lsof -i:$PORT | grep -P 'next-rout \d+' -o | grep -P '\d+' -o)
    fi
fi

echo $PROJECT: $OUTPUT >> /home/maxime/automatics/memo/auto_run.txt

cd ..
